// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

// Default [FirebaseOptions] for use with your Firebase apps.
//
// Example:
// ```dart
// import 'firebase_options.dart';
// // ...
// await Firebase.initializeApp(
//   options: DefaultFirebaseOptions.currentPlatform,
// );
// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAO7jAbgElySegF2U5Xb2mEvDeTrldoZvM',
    appId: '1:919541295083:web:f822ecaf53c85d3d4d5bae',
    messagingSenderId: '919541295083',
    projectId: 'ucsc-canteen-19001355',
    authDomain: 'ucsc-canteen-19001355.firebaseapp.com',
    storageBucket: 'ucsc-canteen-19001355.appspot.com',
    measurementId: 'G-1ZKL7BP622',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7rYTEujebyc33V94Kke7jHK0cetdbcmw',
    appId: '1:919541295083:android:1be09fecca0ec43c4d5bae',
    messagingSenderId: '919541295083',
    projectId: 'ucsc-canteen-19001355',
    storageBucket: 'ucsc-canteen-19001355.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDShwWU0mEB5Bgsycssq8f_4zGsg3LZmsc',
    appId: '1:919541295083:ios:2ae42bb5ffa8e1464d5bae',
    messagingSenderId: '919541295083',
    projectId: 'ucsc-canteen-19001355',
    storageBucket: 'ucsc-canteen-19001355.appspot.com',
    iosClientId:
        '919541295083-lgvvpgqp9jihsq1nt6quueifpl928mpj.apps.googleusercontent.com',
    iosBundleId: 'com.example.ucscCanteen19001355',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDShwWU0mEB5Bgsycssq8f_4zGsg3LZmsc',
    appId: '1:919541295083:ios:2ae42bb5ffa8e1464d5bae',
    messagingSenderId: '919541295083',
    projectId: 'ucsc-canteen-19001355',
    storageBucket: 'ucsc-canteen-19001355.appspot.com',
    iosClientId:
        '919541295083-lgvvpgqp9jihsq1nt6quueifpl928mpj.apps.googleusercontent.com',
    iosBundleId: 'com.example.ucscCanteen19001355',
  );
}
